[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirects for internationalization
[[redirects]]
  from = "/"
  to = "/en"
  status = 301
  conditions = {Language = ["en"]}

[[redirects]]
  from = "/"
  to = "/es"
  status = 301
  conditions = {Language = ["es"]}

[[redirects]]
  from = "/"
  to = "/fr"
  status = 301
  conditions = {Language = ["fr"]}

# Default redirect if no language preference
[[redirects]]
  from = "/"
  to = "/en"
  status = 301
  force = false

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (add actual values in Netlify dashboard)
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"